//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Message
    {
        public int Id { get; set; }
        public string MsgTitle { get; set; }
        public string MsgContent { get; set; }
        public string MsgType { get; set; }
        public string Url { get; set; }
        public System.Guid ToUser { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool IsRead { get; set; }
        public bool IsDel { get; set; }
    }
}
